### PR TITLE
Fixed logging setup to create new logger instead of using root logger

### PR DESCRIPTION
**Pull request by tingwai-to**
When importing `websocket_client.py`, `basicConfig` uses the root logger which can conflict with other `basicConfig` setups. This will create a separate logger for `websocket_client.py`

### CODE REVIEW

**Comment by slazarov** [comment]
And that's how I learn by loggers 👍 . I will test it and merge it. Thank you @tingwai-to.

**Comment by slazarov** [comment]
@tingwai-to since _auxiliary.py uses logging as well. Do you think that creating a custom logging class and placing it in _auxiliary.py would be more efficient. I.e 
```python
class CustomLogger(object):
    def __init__(self,name):
        self.logger = logging.getLogger(name)
        self.logger.setLevel(logging.DEBUG)
        handler = logging.StreamHandler()
        handler.setLevel(logging.DEBUG)
        formatter = logging.Formatter(logging.BASIC_FORMAT)
        handler.setFormatter(formatter)
        self.logger.addHandler(handler)
```
Call it:
```python
self.log=CustomLogger(__name__)
```

**Comment by tingwai-to** [comment]
Oh I didn't notice `_auxiliary.py` uses logging too. That would work, but imo wrapping it in a class would be a little overkill unless you plan on adding other methods. A simple function is probably enough.
```python
def setup_stream_logger(name):
    self.logger = logging.getLogger(name)
    self.logger.setLevel(logging.DEBUG)
    handler = logging.StreamHandler()
    handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter(logging.BASIC_FORMAT)
    handler.setFormatter(formatter)
    self.logger.addHandler(handler)
```
then call it with `setup_stream_logger(__name__)`

**Comment by slazarov** [comment]
@tingwai-to Looks ok?
https://github.com/slazarov/python-bittrex-websocket/tree/v0.0.5/bittrex_websocket

**Comment by tingwai-to** [comment]
Looks good to me. I trust you've tested it :smiley:

**Comment by slazarov** [comment]
I did test it and it looked OK. Can you confirm that it works for you as well?

**Comment by tingwai-to** [comment]
So importing `bittrex-websocket` no longer overwrites my logger config but it still outputs debug messages into my console, which isn't ideal in case I want to change the logging level or turn it off completely. I did some digging, check out this how to.
https://docs.python.org/3.6/howto/logging.html#configuring-logging-for-a-library

Seems like setting up logging on a library might be different from what I normally do. Let me commit some code and see what you think about it

**Comment by tingwai-to** [comment]
Based off of `__init__.py` files from other standard libraries (urllib3, requests) I think this is how it's supposed to be done. 
https://github.com/tingwai-to/python-bittrex-websocket/commit/8f9f7512fc4aa1fca11841c521be68672afddc27

This way your websocket logs are still preserved and if people want to see them, they'll call `bittrex_websocket.add_stream_logger()` which will allow your websocket logs to show up in the developer's logs. I don't know if I can add the above commit to this PR since its on a different branch, so let me know if we need to open a new PR

**Comment by slazarov** [comment]
Thanks, I will take a look at it later. You can make a new PR at the 0.0.5 branch if you want.

**Pull request closed without merging**
